# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # manually
  workflow_dispatch:
  # Triggers the workflow on push or pull request events but only for the "mergeMap" branch
  push:
    paths-ignore:
      - '.github/**'
      - '.coverage/**'
      - '.node_modules/**'
      - '.dist/**'
      - '**.md'
      - '**.gitignore'
      - '**.eslintrc.js'
  

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  main:
    name: test 
    # The type of runner that the job will run on
    runs-on: ubuntu-lates
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@master
      
      # Setup Node.js environment
      - uses: actions/setup-node@v3.3.0
      
      # Install npm dependencies
      - run: npm i
      
      # Lint code style
      - run: npx eslint --ignore-path ./.gitignore '.'

      # Run unit tests
      - run: npx ng test --no-watch --code-coverage
    
      # upload code coverage
      - uses: codecov/codecov-action@v2
        with:
          verbose: true # optional (default = false)
